/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.AbstractObjekat;
import domen.Dobavljac;
import domen.Menadzer;
import domen.Narudzbenica;
import domen.Proizvod;
import domen.StavkaNarudzbenice;
import exception.ValidacijaException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import model.ModelTabeleProizvod;
import model.ModelTabeleStavki;

/**
 *
 * @author Andjelka
 */
public class UnosNarudzbeniceFrm extends javax.swing.JFrame {

    JFrame glavna;
    String status;
    ModelTabeleStavki mts;
    Narudzbenica narudzbenica;
    ModelTabeleProizvod mtp;
    
    /**
     * Creates new form UnosNarudzbeniceFrm
     */
    public UnosNarudzbeniceFrm() {
        initComponents();
    }
    
    public UnosNarudzbeniceFrm(JFrame glavna,Menadzer menadzer) {
        initComponents();
        this.glavna = glavna;
        this.setTitle("Unos narudžbenice");
        narudzbenica = new Narudzbenica("0", new Date(), 0.0, menadzer, null);
        popuniTabeluProizvodi();
        this.status = "unos";
        popuniCBDobavljaci();
        srediFormu();
        srediTabelu();
    }

    UnosNarudzbeniceFrm(JFrame forma, Menadzer ulogovan, Narudzbenica narudzbenica) {
        initComponents();
        this.setTitle("Izmena narudžbenice");
        this.glavna = forma;
        this.status = "izmena";
        popuniTabeluProizvodi();
        popuniCBDobavljaci();
        this.narudzbenica = narudzbenica;
    
        srediTabelu();
        srediFormu(narudzbenica);
            
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNarudzbenicaID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtMenadzer = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbDobavljac = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUkupno = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnIzbrisi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaStavki = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaProizvodi = new javax.swing.JTable();
        btnDodaj = new javax.swing.JButton();
        txtDatum = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("NarudžbenicaID:");

        jLabel2.setText("Menadžer: ");

        jLabel3.setText("Dobavljač:");

        cmbDobavljac.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Datum:");

        jLabel5.setText("Ukupno:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Stavke narudžbenice"));

        btnIzbrisi.setText("Izbriši stavku");
        btnIzbrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzbrisiActionPerformed(evt);
            }
        });

        tabelaStavki.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaStavki);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIzbrisi, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIzbrisi)
                .addGap(7, 7, 7))
        );

        jButton1.setText("Sačuvaj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Proizvodi"));

        tabelaProizvodi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabelaProizvodi);

        btnDodaj.setText("Dodaj proizvod");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtNarudzbenicaID, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMenadzer, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbDobavljac, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtUkupno, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNarudzbenicaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMenadzer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbDobavljac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(txtUkupno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
           int red = tabelaProizvodi.getSelectedRow();
        if (red != -1) {
            Proizvod p = (Proizvod) mtp.getLista().get(red);
            mts.dodajStavku(p, narudzbenica);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Izaberite proizvod koji želite da dodate!");
        }
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnIzbrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzbrisiActionPerformed
         int red = tabelaStavki.getSelectedRow();
        if (red != -1) {
            mts.izbaciStavku(red);
            mts.postaviRB();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Izaberite stavku koju želite da izbacite!");
        }
    }//GEN-LAST:event_btnIzbrisiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try {
           
           Dobavljac dob = (Dobavljac) cmbDobavljac.getSelectedItem();
           validirajIPostaviVrednosti(dob);
           Narudzbenica nar;
           if (status.equals("unos")) {
                nar = (Narudzbenica) Kontroler.vratiInstancu().sacuvajNarudzbenicu(narudzbenica);
                JOptionPane.showMessageDialog(this, "Uspešno ste sačuvali narudžbenicu:\nID: " + nar.getNarudzbenicaID()+ "\nIznos: " + nar.getUkupno()+ "\nMenadzer: " + nar.getMenadzer().toString(), "Uspešno", JOptionPane.INFORMATION_MESSAGE);
            }else {
                List<AbstractObjekat> listaZaMenjanje = napraviListuStavki();
                narudzbenica.setListaStavki(mts.getLista());
                nar = (Narudzbenica) Kontroler.vratiInstancu().izmeniNarudzbenicu(narudzbenica);
                JOptionPane.showMessageDialog(this, "Izmenjena je narudžbenica:\nID: " + nar.getNarudzbenicaID()+ "\nIznos: " + nar.getUkupno()+ "\nMenadzer: " + nar.getMenadzer().toString(), "Uspešno", JOptionPane.INFORMATION_MESSAGE);
            }
            glavna.setVisible(true);
            dispose();
        } catch (ValidacijaException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
          JOptionPane.showMessageDialog(this, ex.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnosNarudzbeniceFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnosNarudzbeniceFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnosNarudzbeniceFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnosNarudzbeniceFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UnosNarudzbeniceFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnIzbrisi;
    private javax.swing.JComboBox cmbDobavljac;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaProizvodi;
    private javax.swing.JTable tabelaStavki;
    private javax.swing.JTextField txtDatum;
    private javax.swing.JTextField txtMenadzer;
    private javax.swing.JTextField txtNarudzbenicaID;
    private javax.swing.JTextField txtUkupno;
    // End of variables declaration//GEN-END:variables

    private void popuniCBDobavljaci() {

        try {
            List<AbstractObjekat> listaTipova = Kontroler.vratiInstancu().ucitajDobavljace();
            cmbDobavljac.setModel(new DefaultComboBoxModel(listaTipova.toArray()));
            cmbDobavljac.setSelectedItem(null);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private void srediFormu() {

        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        txtDatum.setEnabled(false);
        String datum = sdf.format(narudzbenica.getDatum());
        txtDatum.setText(datum);
        txtNarudzbenicaID.setEnabled(false);
        txtUkupno.setEnabled(false);
        txtMenadzer.setText(narudzbenica.getMenadzer().toString());
        txtMenadzer.setEnabled(false);
        
    }

    private void srediTabelu() {

        mts = new ModelTabeleStavki();
        mts.setTxtIznos(txtUkupno);
        tabelaStavki.setModel(mts);
    }
    
    private void popuniTabeluProizvodi() {
        try {
            List<AbstractObjekat> proizvodi = Kontroler.vratiInstancu().ucitajProizvode();
            mtp = new ModelTabeleProizvod(proizvodi);
            tabelaProizvodi.setModel(mtp);
        } catch (Exception ex) {
            Logger.getLogger(UnosDobavljacaFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void validirajIPostaviVrednosti(Dobavljac dob) throws Exception {


        
        if (dob == null) {
            throw new ValidacijaException("Morate odabrati dobavljaca!");
        }
         
         List<AbstractObjekat> listaStavki = mts.getLista();
        if (listaStavki.isEmpty()) {
            throw new ValidacijaException("Morate uneti makar jednu stavku!");
        }
        
        String iznosNarudzbine = txtUkupno.getText();
        double iznos = Double.parseDouble(iznosNarudzbine);
        narudzbenica.setDobavljac(dob);
       
        narudzbenica.setListaStavki((ArrayList<AbstractObjekat>) listaStavki);
        narudzbenica.setUkupno(iznos);
    }

    private void srediFormu(Narudzbenica narudzbenica) {

        SimpleDateFormat sdf= new SimpleDateFormat("dd.MM.yyyy");
        srediFormu();
        txtNarudzbenicaID.setText(narudzbenica.getNarudzbenicaID());
        txtUkupno.setText(narudzbenica.getUkupno()+ "");
        txtMenadzer.setText(narudzbenica.getMenadzer().toString());
        txtDatum.setText(sdf.format(narudzbenica.getDatum()));
        cmbDobavljac.setSelectedItem(narudzbenica.getDobavljac());
        mts.setLista(narudzbenica.getListaStavki());
        mts.popuniOriginalnuListu(narudzbenica.getListaStavki());
        mts.fireTableDataChanged();
    }



        private List<AbstractObjekat> napraviListuStavki() {
        List<AbstractObjekat> listaZaSlanje = new ArrayList<>();
        List<AbstractObjekat> originalnaLista = mts.getOriginalnaLista();
        List<AbstractObjekat> listaStavki = mts.getLista();
        for (AbstractObjekat ao : originalnaLista) {
            StavkaNarudzbenice originalnaStavka = (StavkaNarudzbenice) ao;
            boolean obrisana = true;
            for (AbstractObjekat ao1 : listaStavki) {
                StavkaNarudzbenice stavka = (StavkaNarudzbenice) ao1;
                if (originalnaStavka.getProizvod().equals(stavka.getProizvod())) {
                    obrisana = false;
                    break;
                }
            }
            if (obrisana) {
                originalnaStavka.setStanje("obrisana");
                listaZaSlanje.add(originalnaStavka);
            }
        }
        listaZaSlanje.addAll(listaStavki);
        return listaZaSlanje;
    }
    
}
